required_version = "1.8.0"
edition = "2024"

comment_width = 80
condense_wildcard_suffixes = true
doc_comment_code_block_width = 80
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 80
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
