required_version = "1.4.8"
condense_wildcard_suffixes = true
edition = "2018"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 80
merge_imports = true
normalize_doc_attributes = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
